### ISSUE TITLE
Hi, just leaving a message.

### ISSUE THREAD

**Issue by ChauvelinB** [keganpowers34/minecraft-scan-decompress#1]
Hi! Sorry about kicking you off one of the servers I was on. Just wasn't expecting people at that time. Didn't exactly have good experiences with prior visitors so hit the big red button pretty quick this time.

I do have a public server that less people play on just a few ports away (subtract 2). masscan might've found it, I'll have to find the log.
Anyhoo, happy mining!

**Comment by keganpowers34** [comment]
naa its all good
